# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wk7iAX5JqUUBu7z65wVTzpUPd-_l96WE
"""

!pip install googletrans==4.0.0-rc1

from googletrans import Translator
import ipywidgets as widgets
from IPython.display import display

translator = Translator()

def translate_text( text, target_lang ):
     translated = translator.translate( text,dest=target_lang )
     return translated.text

text_input = widgets.Textarea(
    placeholder="Enter text to translate...",
    layout=widgets.Layout(width="100%",height="100px"))

lang_dropdown = widgets. Dropdown(
options=[("Spanish", "es"), ("French", "fr"), ("German", "de"), ("Hindi", "hi"), ("Chinese", "zh-cn")],
description="Language:")

translate_button = widgets.Button(description="Translate")
output_box = widgets.Output()

def on_translate_clicked(b):
  output_box.clear_output()
  translated_text = translate_text(text_input.value, lang_dropdown.value)
  with output_box:
    print("Translated:", translated_text)

translate_button.on_click(on_translate_clicked)

display(text_input, lang_dropdown, translate_button, output_box)